name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p dist
          cp index.html dist/
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send status and logs to email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Pages Deployment Status"
          body: |
            Deployment status: ${{ job.status }}
            Commit SHA: ${{ github.sha }}\n\n
            Thanks and Regards,
            Tamilvanan Gowran
